apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kubectl
    image: dtzar/helm-kubectl:latest
    command: ["sh"]
    tty: true

  - name: terraform
    image: hashicorp/terraform:latest
    command: 
    - sh
    tty: true
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_ACCESS_KEY_ID

      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY

    volumeMounts:     
      - name: shared-data
        mountPath: /mnt/shared-data                    

  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
    
  - name: aws
    image: amazon/aws-cli
    command:
    - sh
    tty: true
    volumeMounts:     
      - name: shared-data
        mountPath: /mnt/shared-data
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_ACCESS_KEY_ID

      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY                
    
  - name: dind  
    image: docker:dind
    imagePullPolicy: Always
    ports:     
      - containerPort: 2375
        protocol: TCP
    env:     
      - name: DOCKER_TLS_CERTDIR
        value: ""
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
    tty: true
    volumeMounts:     
      - name: dind-storage
        mountPath: /var/lib/docker
      - name: shared-data
        mountPath: /mnt/shared-data
    securityContext:   
      privileged: true          
  
  volumes:  
  - name: dind-storage      
    emptyDir: {}
  - name: shared-data
    emptyDir: {}            
      

