apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-hpa
  # namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

  # metrics:
  #   - type: Resource
  #     resource:
  #       name: cpu
  #       target:
  #         type: Utilization
  #         averageUtilization: 50
